#!/bin/sh
# $FreeBSD$

set -e

scriptdir=$(cd $(dirname $0) && pwd)
fwdir=$scriptdir/../radeonkmsfw-files

for dir in $(find $scriptdir -type d -depth 1); do
	rm -rf $dir
done

for file in $(find $fwdir -name '*.bin'); do
	base=$(basename $file)
	img=${base%.bin}
	echo "Image: $img"

	mkdir -p $scriptdir/$img
	cat > $scriptdir/$img/Makefile <<EOF
# \$FreeBSD$

NAME=	$img

.include <bsd.kmod.mk>
EOF
done
